nelmio_api_doc:
  documentation:
    info:
      title:       "Logs Service"
      description: "This is the API documentation"
      version:     "1.0.0"

  areas: # define where Swagger should be available
    default:
      path_patterns: [ '^/logs' ] # restrict to routes starting with /logs