version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - ./:/var/www/logs-service

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/logs-service

  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: logs_service
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql