services:
  php:
    container_name: logs-service-php
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      CORS_ALLOW_ORIGIN: "*"
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    container_name: logs-service-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '8077:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  database:
    container_name: logs-service-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: logs-service
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4310:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

  redis:
    container_name: logs-service-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6380:6379'
    networks:
      - symfony

  swagger-ui:
    container_name: logs-service-swagger-ui
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - nginx
    environment:
      SWAGGER_JSON_URL: "${SWAGGER_JSON_URL}"
    networks:
      - symfony
networks:
  symfony:
    driver: bridge

volumes:
  mysql_data: