services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Tests\Behavioral\:
        resource: '../tests/Behavioral/*'
doctrine:
    dbal:
        connections:
            default:
                use_savepoints: true