services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behavioral/*'

doctrine:
    dbal:
        connections:
            default:
                use_savepoints: true